version: "3"
services:
  api:
    build: ./api 
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3000:3000"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - data/db:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    command: server --console-address ":9001" http://minio/data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  db:
    driver: local
