version: "3"
services:
    pusher:
        depends_on:
            - api
        restart: always
        build: ./notification
        environment:
            - SecretId=${SecretId}
            - SecretKey=${SecretKey}
            - Bucket=${Bucket}
            - Region=${Region}

            - SELF_HOST=pusher
            - WEBHOOK_HOST=http://api:3000
            - HOOK_TOKEN=api_admin_66618273
            - MINIO_HOST=http://minio:9000
            - PORT=3001
    api:
        depends_on:
            - minio
            - db
        build: ./api
        restart: always
        environment:
            # 以下的两个token涉及到内部的访问权限 admin 拥有管理权限，而 readable 只有读取的部分权限
            - ADMIN_TOKEN=api_admin_66618273
            - READABLE_TOKEN=api_readable_4173
            - CORS_ORIGIN=*

            - DB_HOST=db
            - PREVIEW_TEXT="中文网字计划\nAaBbCc"
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - MINIO_POINT=minio
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin

        ports:
            - "3000:3000"
        healthcheck:
            test: node ./test/healthcheck.mjs || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        expose:
            - 5432
        volumes:
            - ./data/db:/var/lib/postgresql/data
        # postgres 数据库需要等待端口启动，才不会导致其它程序 bug
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 10s
            retries: 5
    minio:
        image: minio/minio:RELEASE.2023-05-04T21-44-30Z
        command: server --console-address ":9001" /data
        restart: always
        expose:
            - 9000
        ports:
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        volumes:
            - ./data/minio/data:/data
            - ./data/minio/config:/root/.minio/
