version: "3"
services:
    api:
        depends_on:
            - minio
            - db
        build: ./api
        environment:
            - DB_HOST=db
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - MINIO_POINT=minio
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        ports:
            - "3000:3000"
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
    minio:
        image: minio/minio:RELEASE.2023-05-04T21-44-30Z
        command: server --console-address ":9001" /data
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        volumes:
            - ./data/minio/data:/data
            - ./data/minio/config:/root/.minio/
